# Generated by Django 3.1 on 2021-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211218_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.CharField(default='Anonymous', max_length=140),
        ),
    ]
