# Generated by Django 3.1 on 2021-12-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(default='Anonymous', max_length=140),
        ),
    ]
